// Auto-generated by merge-ego.cjs
import raw from './ego.json';
export interface EgoEntry { id:string; name:string; slug:string; rarity:string; character:string; season:string; sanityCost:string; affinity:string; source:string; speciality:string[]; cost:Record<string,number>; isNew:boolean; image:string; url:string; }
// eslint-disable-next-line
export const egoById: Record<string, EgoEntry> = raw as unknown as Record<string, EgoEntry>;
export const egoEntries: EgoEntry[] = Object.values(egoById);
export function getEgoById(id: string): EgoEntry | null { return egoById[id] ?? null; }
export function getEgoImage(egoId: string): string {
  return egoById[egoId]?.image ?? `/assets/ego_output/images/ego_${egoId}_sm.jpg`;
}
