// Auto-generated by merge-ego.cjs
import raw from './ego.json';
export interface EgoEntry {
  id: string;
  name: string;
  slug: string;
  rarity: string;
  character: string;
  season: string;
  sanityCost: string;
  affinity: string;
  source: string;
  speciality: string[];
  cost: Record<string, number>;
  isNew: boolean;
  image: string;
  url: string;
}

export const egoById: Record<string, EgoEntry> = (raw as EgoEntry[]).reduce((acc, entry) => {
  acc[entry.id] = entry;
  return acc;
}, {} as Record<string, EgoEntry>);

export const egoEntries: EgoEntry[] = raw as EgoEntry[];
export function getEgoById(id: string): EgoEntry | null { return egoById[id] ?? null; }
export function getEgoImage(egoId: string): string {
  const ego = egoById[egoId];
  if (ego && ego.image) {
    return ego.image;
  }
  
  // Handlers for unconventional ID formats or fallbacks if not in JSON
  const egoIdAsNumber = Number(egoId);
  if (!isNaN(egoIdAsNumber)) {
    return `/assets/ego/images/ego_${egoIdAsNumber}_sm.jpg`;
  }

  return '/favicon.svg';
}
